apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: int-env-audit-app
  namespace: argocd
spec:
  project: Project1

  source:
    repoURL: https://github.com/dhruvraapid/argocd_environments.git 
    targetRevision: HEAD

    path: argo_code

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
