apiVersion: apps/v1
kind: Deployment
metadata:
  name: int-myapp-deployment
spec:
  selector:
    matchLabels:
      app: int-myapp-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: int-myapp-deployment
    spec:
      containers:
      - name: int-myapp-deployment
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
