apiVersion: apps/v1
kind: Deployment
metadata:
  name: qamyapp
spec:
  selector:
    matchLabels:
      app: qamyapp
  replicas: 2
  template:
    metadata:
      labels:
        app: qamyapp
    spec:
      containers:
      - name: qamyapp
        image: nanajanashia/argocd-app:1.2 
        ports:
        - containerPort: 8080
